# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c789b96909e9a412da29ad48b10798caf9fbb21d21626722933551628978d79840b0810d8ac27ba030e80217c4662f9dac84de644bf904b4b58cecad65dc2009

test:
  secret_key_base: a354a7e07dd0162ee017066f7d6d316952f0e44fb3f18cb113191b4144ac4a86690699824eefa2951eca6db5c1ec222446c2057dc32e6a7ef762503a8af5023e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
